name: Link Checker

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 0 1 * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check URLs
        uses: paramt/url-checker@master
        with:
          files: "README.md"
          blacklist: "https://github.com/schulle4u/awesome-yellow/blob/master/LICENSE,https://awesome.re,https://awesome.re/badge.svg,https://img.shields.io/badge/License-CC0-blue.svg,https://creativecommons.org/publicdomain/zero/1.0/,https://example.com,https://github.com/sindresorhus/awesome"